import pandas as pd
df = pd.read_excel("data/Telco_customer_churn.xlsx")
print ("First 5 rows of the data")
print(df.head())
print("\nInformation about the dataset:")
df.info()
print("\nStatistical summary of numerical coloumns:")
print(df.describe())
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors = 'coerce')
print("\nMissing values after cleaning 'Total Charges':")
print(df.isnull().sum())
df['Total Charges'].fillna(df['Total Charges'].median(), inplace=True)
print("\nMissing values after filling:")
print(df.isnull().sum())
df.drop('CustomerID', axis=1, inplace = True)
print("\nDropped 'CustomerID' column. First 5 rows now:")
print(df.head())
df['Churn Value'] = df['Churn Value'].apply(lambda x: 1 if x == 'Yes' else 0)
df_processed = pd.get_dummies(df, drop_first=True)
print("\nData after converting text columns into numbers (One-Hot Encoding):")
print(df_processed.head())